In [17]:
import numpy as np

C="Cat"
F="Fish"
H="Hen"
y_true = [C,C,C,C,C,C, F,F,F,F,F,F,F,F,F,F, H,H,H,H,H,H,H,H,H]
y_pred = [C,C,C,C,H,F, C,C,C,C,C,C,H,H,F,F, C,C,C,H,H,H,H,H,H]

mapping = {C:0, F:1, H:2} # Mapping your classes to numeric values
confusion_matrix = np.zeros((3, 3))
total_correct = 0

for t, p in zip(y_true, y_pred):
    confusion_matrix[mapping[t], mapping[p]] += 1
    if t == p:
        total_correct += 1

macro_precision = np.zeros(3)
macro_recall = np.zeros(3)
macro_f1score = np.zeros(3)
support = np.zeros(3)

for i in range(3):
    macro_precision[i] = confusion_matrix[i, i] / confusion_matrix[:, i].sum()
    macro_recall[i] = confusion_matrix[i, i] / confusion_matrix[i, :].sum()
    support[i] = confusion_matrix[i, :].sum()
    macro_f1score[i] = 2 * ((macro_precision[i] * macro_recall[i]) / (macro_precision[i] + macro_recall[i]))

macro_avg_precision = np.mean(macro_precision)
macro_avg_recall = np.mean(macro_recall)
macro_avg_f1_score = np.mean(macro_f1score)
weighted_avg_precision = np.dot(macro_precision, support) / np.sum(support)
weighted_avg_recall = np.dot(macro_recall, support) / np.sum(support)
weighted_avg_f1_score = np.dot(macro_f1score, support) / np.sum(support)

print('Confusion Matrix:')
print(confusion_matrix)
print()
print('Accuracy: ', total_correct / len(y_true))
print('Macro Avg Precision: ', macro_avg_precision)
print('Macro Avg Recall: ', macro_avg_recall)
print('Macro Avg F1 Score: ', macro_avg_f1_score)
print('Weighted Avg Precision: ', weighted_avg_precision)
print('Weighted Avg Recall: ', weighted_avg_recall)
print('Weighted Avg F1 Score: ', weighted_avg_f1_score)
print('Precision for each class: ', macro_precision)
print('Recall for each class: ', macro_recall)
print('F1Score for each class: ', macro_f1score)
print('Support for each class:', support)


Confusion Matrix:
[[4. 1. 1.]
 [6. 2. 2.]
 [3. 0. 6.]]

Accuracy:  0.48
Macro Avg Precision:  0.547008547008547
Macro Avg Recall:  0.5111111111111111
Macro Avg F1 Score:  0.46513720197930725
Weighted Avg Precision:  0.5805128205128205
Weighted Avg Recall:  0.48
Weighted Avg F1 Score:  0.46412955465587047
Precision for each class:  [0.30769231 0.66666667 0.66666667]
Recall for each class:  [0.66666667 0.2        0.66666667]
F1Score for each class:  [0.42105263 0.30769231 0.66666667]
Support for each class: [ 6. 10.  9.]
